version: "2"

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_extensions:/opt/sonarqube/extensions

  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    user: root
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./home:/home
      - /var/run/docker.sock:/var/run/docker.sock    

  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: always
    volumes:
      # Remove the /var/run/docker.sock volume if running on Windows
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  hound:
    container_name: hound
    image: etsy/hound:latest
    restart: always
    volumes:
      - ./hound/config.json:/data/config.json
      - ./hound/data:/data/data

  nginx:
      container_name: nginx
      image: nginx:latest
      restart: always
      ports:
        - 80:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgresql:
  postgresql_data:
  portainer_data:

  